server:
  port: 7011
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7010/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xzh888906/huarui.git
          username: xzh888906
          password: xzh@770207
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
