env: dev
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7010/eureka/
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
server:
  port: 7012
spring:
  application:
    name: gateway
  cloud:
    config:
      server:
        git:
          password: xzh@770207
          uri: https://github.com/xzh888906/huarui.git
          username: xzh888906
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
 # retryable: true    #重试必配
  routes:
      auth:
        path: /uaa/**
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000      
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
security:
  oauth2:
    sso:
      login-path: /login
    client:
      access-token-uri: http://127.0.0.1:7013/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7013/uaa/oauth/authorize
      client-id: client
      client-secret: secret
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhrXaWLMQMvEI3X+x1UrL5JfeB81iGkKIR2DKUQYxpGeMF4eFRM9TOpa5cyhtSLerns45I/xHewqV02kIOSaJL1JeYj2yf0X5w7rPl/Q43c9WxSuLHJCto7FEA56Oz/xf+rikW94rhA7hwKp6CZ9C8UlBmbpFoGZTRVHKeR0gKsNOo7Rerh9Njx2h/+v51AY02YqSccIRKUXjWNscMNkVJRqHnaya9IVIcUpXZ5Pi3zKMvuS2QCbBfvoH28ciHQ/ZJLXUjDzAqVzIAR4vPBK/wqW1T1qpeEmnOa/RDB7LKZw0DtPvF27g1zoBEbKsOghoaRqzOgXdhYUYjso/zBshrwIDAQAB
                   -----END PUBLIC KEY-----
      id: gateway
      service-id: gateway
      loadBalanced: true
