env: dev
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7010/eureka/
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
server:
  port: 7012
spring:
  application:
    name: gateway
  cloud:
    config:
      server:
        git:
          password: xzh@770207
          uri: https://github.com/xzh888906/huarui.git
          username: xzh888906
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000      
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
