server:
  port: 7012
spring:
  application:
    name: gateway 
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7010/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000    
 
env:
  dev
