server:
  port: 7014

spring:
  application:
    name: shop
  devtools:
      restart:
        enabled: true
  datasource:
      name: mytest
      url: jdbc:mysql://127.0.0.1:3306/cloud_huarui?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7010/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.huarui.user.bean

